-- Add profile fields
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS name VARCHAR(50),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS state_prefecture VARCHAR(100),
ADD COLUMN IF NOT EXISTS city VARCHAR(100),
ADD COLUMN IF NOT EXISTS plane_registration VARCHAR(8),
ADD COLUMN IF NOT EXISTS plane_model_make VARCHAR(50);